apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-02-20T09:38:02Z"
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/managed-by: example-argocd
    app.kubernetes.io/name: example-argocd-server
    app.kubernetes.io/part-of: argocd
  name: example-argocd-server
  namespace: default
  ownerReferences:
  - apiVersion: argoproj.io/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: ArgoCD
    name: example-argocd
    uid: e1f0a200-39cd-40aa-819f-fa0124a420dd
  resourceVersion: "9633"
  uid: 982a36b7-989a-4b56-9b1d-dd4400aa1890
spec:
  clusterIP: 10.107.151.104
  clusterIPs:
  - 10.107.151.104
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: example-argocd-server
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
