---
# tasks file for roles/base
- name: Update all packages to the latest version
  apt:
    update_cache: yes
    upgrade: dist
  become: yes

- name: Install basic utilities
  apt:
    name:
      - curl
      - vim
      - git
      - htop
    state: present
  become: yes

- name: Install fail2ban
  apt:
    name: fail2ban
    state: present
  become: yes

- name: Ensure fail2ban service is running and enabled
  service:
    name: fail2ban
    state: started
    enabled: yes
  become: yes

